"""Tests for scripts/build_playground.py (letter selection and export format)."""

import json

import numpy as np

from scripts import build_playground as B

CLASSES = np.array(list("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"))


def _members(n=400, seeds=5, seed=0):
    """Synthetic ensemble members with every situation the page shows."""
    rng = np.random.default_rng(seed)
    true = rng.integers(0, 52, n)
    members = []
    for s in range(seeds):
        p = np.full((n, 52), 0.05 / 51)
        p[np.arange(n), true] = 0.95
        # A block of case splits: every member about 50/50 between a letter
        # and its other case.
        for i in range(0, 60):
            other = (true[i] + 26) % 52
            p[i] = 0.02 / 50
            p[i, true[i]], p[i, other] = 0.5, 0.48
        # A block where each member confidently picks a different letter.
        for i in range(60, 120):
            p[i] = 0.1 / 51
            p[i, (true[i] + s + 1) % 52] = 0.9
        members.append(
            {
                "true": true,
                "proba": p / p.sum(1, keepdims=True),
                "handedness": np.full(n, -1),
                "classes": CLASSES,
                "seed": s,
                "split": "official both/indep/fold0, writer-independent",
                "model": "cnn_bilstm_attn",
            }
        )
    return members


def test_letters_cover_every_situation_with_distinct_letters():
    chosen = B.pick_letters(_members())
    kinds = {}
    for kind, i in chosen:
        kinds.setdefault(kind, []).append(i)
    assert set(kinds) == {"clear", "case", "disagree"}
    true = _members()[0]["true"]
    for idx in kinds.values():
        assert len(idx) <= B.PER_KIND
        assert len({int(true[i]) for i in idx}) == len(idx)


def test_disagreeing_letters_come_from_the_disagreement_block():
    chosen = B.pick_letters(_members())
    assert all(60 <= i < 120 for kind, i in chosen if kind == "disagree")
    assert all(i < 60 for kind, i in chosen if kind == "case")


def test_exported_records_hold_every_member_and_the_mean():
    members = _members()
    rec = B.letter_records(members, [("clear", 200)], {"right": members})[0]
    assert rec["label"] == str(CLASSES[members[0]["true"][200]])
    assert len(rec["right"]["members"]) == 5
    assert np.allclose(
        np.mean(rec["right"]["members"], 0), rec["right"]["mean"], atol=1e-3
    )


def test_group_summary_scores_the_ensemble_mean():
    summary = B.group_summary(_members())
    # Rows 60-119: every member picks a different wrong letter, and so does
    # the mean. Everything else is right: 340 of 400.
    assert summary["n_test"] == 400
    assert summary["ensemble_accuracy"] == 85.0


def test_written_file_is_a_script_assigning_json(tmp_path):
    path = tmp_path / "out.js"
    B.write_js(str(path), "PLAYGROUND_TEST", {"a": [1, 2]})
    text = path.read_text(encoding="utf-8")
    assert text.startswith("// Generated by scripts/build_playground.py")
    body = text.split("window.PLAYGROUND_TEST = ", 1)[1].rstrip().rstrip(";")
    assert json.loads(body) == {"a": [1, 2]}


def test_synthetic_signal_goes_through_every_filter():
    versions = B.filtered_versions(B.synthetic_signal())
    assert set(versions) == {"none", "lowpass", "orientation"}
    assert all(len(v) == 13 for v in versions.values())
    assert versions["lowpass"] != versions["none"]
